import { CardType } from "../pages/Home/model/types/cardsType";

export const cards2: CardType[] = [
    {
        "id": "1",
        "post": "frontend-developer",
        "name": "frontend-developer",
        "department": "3",
        "date_open": "2025-02-19",
        "date_close": "2025-02-27",
        "sex": "Мужской",
        "education": "Высшее",
        "salary": "На руки",
        "from": "60000",
        "to": "120000",
        "region": "Москва",
        "address": "Студенческая, 33",
        "metro": "Студенческая",
        "experience": "есть",
        "schedule": "Полный день",
        "type": "Полная занятость",
        "responsibilities": "la",
        "skills": "li",
        "advantages": "lo"
    },
    {
        "id": "2",
        "post": "frontend-developer",
        "name": "frontend-developer",
        "department": "3",
        "date_open": "2025-02-19",
        "date_close": "2025-02-27",
        "sex": "Мужской",
        "education": "Высшее",
        "salary": "На руки",
        "from": "60000",
        "to": "120000",
        "region": "Москва",
        "address": "Студенческая, 33",
        "metro": "Студенческая",
        "experience": "есть",
        "schedule": "Полный день",
        "type": "Полная занятость",
        "responsibilities": "la",
        "skills": "li",
        "advantages": "lo"
    },
    {
        "id": "3",
        "post": "frontend-developer",
        "name": "frontend-developer",
        "department": "3",
        "date_open": "2025-02-19",
        "date_close": "2025-02-27",
        "sex": "Мужской",
        "education": "Высшее",
        "salary": "На руки",
        "from": "60000",
        "to": "120000",
        "region": "Москва",
        "address": "Студенческая, 33",
        "metro": "Студенческая",
        "experience": "есть",
        "schedule": "Полный день",
        "type": "Полная занятость",
        "responsibilities": "la",
        "skills": "li",
        "advantages": "lo"
    },
]