export type CardType = {
    id: string,
    post: string,
    name: string,
    department: string,
    date_open: string,
    date_close: string,
    sex: string,
    education: string,
    salary: string,
    from: string,
    to: string,
    region: string,
    address: string,
    metro: string,
    experience: string,
    schedule: string,
    type: string,
    responsibilities: string,
    skills: string,
    advantages: string
}

// "id": "4",
// "post": "frontend-developer",
// "name": "frontend-developer",
// "department": "3",
// "date_open": "2025-02-19",
// "date_close": "2025-02-27",
// "sex": "Мужской",
// "education": "Высшее",
// "salary": "На руки",
// "from": "60000",
// "to": "120000",
// "region": "Москва",
// "address": "Студенческая, 33",
// "metro": "Студенческая",
// "experience": "есть",
// "schedule": "Полный день",
// "type": "Полная занятость",
// "responsibilities": "la",
// "skills": "li",
// "advantages": "lo"